# Generated by Django 5.1.1 on 2024-10-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_entrylog_remove_tagentry_people_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
